create database QL_Diem

use QL_Diem
GO

CREATE TABLE [dbo].[PHANQUYEN] (MaPhanQuyen INT PRIMARY KEY NOT NULL,TenPhanQuyen NVARCHAR (MAX) NULL)

CREATE TABLE [dbo].[GIAOVIEN] (MaGV NCHAR(20) PRIMARY KEY NOT NULL, TenGV NVARCHAR (MAX) NULL,NgaySinh DATETIME,GioiTinh NVARCHAR(20),SoDienThoai NVARCHAR(20),DiaChi NVARCHAR(MAX),HinhAnh NVARCHAR(MAX))

CREATE TABLE [dbo].[TAIKHOAN] (MaTK INT PRIMARY KEY IDENTITY (1, 1) NOT NULL,TaiKhoan NCHAR(30) NULL,MatKhau NCHAR (30) NULL,MaPhanQuyen INT REFERENCES PHANQUYEN NOT NULL,MaGV NCHAR(20) REFERENCES GIAOVIEN NOT NULL)

CREATE TABLE [dbo].[KHOILOP] (MaKhoi NCHAR(20) PRIMARY KEY NOT NULL, TenKhoi NVARCHAR (100) NULL)

CREATE TABLE [dbo].[NAMHOC] (MaNamHoc NCHAR(20) PRIMARY KEY,TenNamHoc NVARCHAR(50))

CREATE TABLE [dbo].[LOP] (MaLop NCHAR(20) PRIMARY KEY NOT NULL,TenLop NVARCHAR(MAX) NULL,MaGV NCHAR(20) REFERENCES GIAOVIEN NOT NULL,MaKhoi NCHAR(20) REFERENCES KHOILOP NOT NULL,MaNamHoc NCHAR(20) REFERENCES NAMHOC)

CREATE TABLE [dbo].[HOCSINH] (MaHS NCHAR(20) PRIMARY KEY NOT NULL, TenHS NVARCHAR(MAX) NULL, MaLop NCHAR(20) REFERENCES LOP NOT NULL,NgaySinh DATETIME NULL,GioiTinh NVARCHAR (20) NULL,DiaChi NVARCHAR (MAX) NULL,HinhAnh NVARCHAR(MAX))

CREATE TABLE [dbo].[MONHOC] (MaMH NCHAR(20) PRIMARY KEY NOT NULL,TenMH NVARCHAR (MAX) NULL)

CREATE TABLE [dbo].[HOCKY] (MaHK NCHAR(5) PRIMARY KEY,TenHK NVARCHAR(20))

CREATE TABLE [dbo].[BANGDIEM] (MaBD INT PRIMARY KEY IDENTITY (1, 1) NOT NULL,MaHS NCHAR(20) REFERENCES HOCSINH NOT NULL,MaMH NCHAR(20) REFERENCES MONHOC NOT NULL, DiemMieng NUMERIC(18) NULL, Diem15Phut NUMERIC(18) NULL,Diem1Tiet NUMERIC(18) NULL,DiemHK NUMERIC(18) NULL,MaHK NCHAR(5) REFERENCES HOCKY)

INSERT INTO PHANQUYEN VALUES(1,'Admin')
INSERT INTO PHANQUYEN VALUES(2,'Giao Vien')

INSERT INTO HOCKY VALUES ('HK1',N'Học Kỳ I')
INSERT INTO HOCKY VALUES ('HK2',N'Học Kỳ II')

INSERT INTO NAMHOC VALUES('nh01','2020-2021')

INSERT INTO MONHOC VALUES('TO10',N'Toán 10')
INSERT INTO MONHOC VALUES('NV10',N'Ngữ Văn 10')
INSERT INTO MONHOC VALUES('AC10',N'Anh Văn 10')
INSERT INTO MONHOC VALUES('LS10',N'Lịch Sử 10')
INSERT INTO MONHOC VALUES('DL10',N'Địa lý 10')
INSERT INTO MONHOC VALUES('GDCD10',N'GDCD 10')
INSERT INTO MONHOC VALUES('TI10',N'Tin học 10')
INSERT INTO MONHOC VALUES('S10',N'Sinh học 10')
INSERT INTO MONHOC VALUES('VA10',N'Vật lý 10')
INSERT INTO MONHOC VALUES('H10',N'Hóa học 10')

INSERT INTO MONHOC VALUES('TO11',N'Toán 11')
INSERT INTO MONHOC VALUES('NV11',N'Ngữ Văn 11')
INSERT INTO MONHOC VALUES('AC11',N'Anh Văn 11')
INSERT INTO MONHOC VALUES('LS11',N'Lịch Sử 11')
INSERT INTO MONHOC VALUES('DL11',N'Địa lý 11')
INSERT INTO MONHOC VALUES('GDCD11',N'GDCD 11')
INSERT INTO MONHOC VALUES('TI11',N'Tin học 11')
INSERT INTO MONHOC VALUES('S11',N'Sinh học 11')
INSERT INTO MONHOC VALUES('VA11',N'Vật lý 11')
INSERT INTO MONHOC VALUES('H11',N'Hóa học 11')

INSERT INTO MONHOC VALUES('TO12',N'Toán 12')
INSERT INTO MONHOC VALUES('NV12',N'Ngữ Văn 12')
INSERT INTO MONHOC VALUES('AC12',N'Anh Văn 12')
INSERT INTO MONHOC VALUES('LS12',N'Lịch Sử 12')
INSERT INTO MONHOC VALUES('DL12',N'Địa lý 12')
INSERT INTO MONHOC VALUES('GDCD12',N'GDCD 12')
INSERT INTO MONHOC VALUES('TI12',N'Tin học 12')
INSERT INTO MONHOC VALUES('S12',N'Sinh học 12')
INSERT INTO MONHOC VALUES('VA12',N'Vật lý 12')
INSERT INTO MONHOC VALUES('H12',N'Hóa học 12')

INSERT INTO GIAOVIEN VALUES ('admin','admin','','','','','')
INSERT INTO GIAOVIEN VALUES ('GV01',N'Võ Văn Khang',CONVERT(datetime,'15/08/1999',103),N'Nam','0123456789',N'Quảng Nam','')
INSERT INTO GIAOVIEN VALUES ('GV02',N'Võ Văn An',CONVERT(datetime,'15/08/1999',103),N'Nam','0123456789',N'Quảng Nam','')
INSERT INTO GIAOVIEN VALUES ('GV03',N'Võ Thị Quỳnh Nhung',CONVERT(datetime,'17/03/1999',103),N'Nữ','0123456789',N'Đà Nẵng','')
INSERT INTO GIAOVIEN VALUES ('GV04',N'Lê Thị Loan',CONVERT(datetime,'17/03/1999',103),N'Nữ','0123456789',N'Đà Nẵng','')
INSERT INTO GIAOVIEN VALUES ('GV05',N'Trần Gia Hưng',CONVERT(datetime,'17/03/1999',103),N'Nam','0123456789',N'Tam Kỳ','')

INSERT INTO TAIKHOAN VALUES('admin','admin',1,'admin')
INSERT INTO TAIKHOAN VALUES('khang','123456',2,'GV01')
INSERT INTO TAIKHOAN VALUES('vanan','123456',2,'GV02')
INSERT INTO TAIKHOAN VALUES('nhung','123456',2,'GV03')
INSERT INTO TAIKHOAN VALUES('loanle','123456',2,'GV04')
INSERT INTO TAIKHOAN VALUES('giahung','123456',2,'GV05')

INSERT INTO KHOILOP VALUES('KH01',N'Khối lớp 10')
INSERT INTO KHOILOP VALUES('KH02',N'Khối lớp 11')
INSERT INTO KHOILOP VALUES('KH03',N'Khối lớp 12')

SELECT * FROM GIAOVIEN
SELECT * FROM TAIKHOAN
SELECT * FROM MONHOC